stages: # List of stages for jobs, and their order of execution
  - check
  - build-base
  - publish
  - post-publish
  - prerelease
  - release
  - whisper-build

include:
  - local: ".gitlab/ci/check.yml"
  - local: ".gitlab/ci/base-images.yml"
  - local: ".gitlab/ci/bump-versions.yml"
  - local: ".gitlab/ci/publish-web.yml"
  - local: ".gitlab/ci/publish-packages.yml"
  - local: ".gitlab/ci/publish-mobile.yml"
  - local: ".gitlab/ci/whisper-build.yml"
