nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

preferDeferredVersions: true

changesetIgnorePatterns:
  - "**/*.test.{js,ts,jsx,tsx}"
  - "**/__fixtures/**/*"
  - package.json
  - "**/tsconfig.json"
  - "**/README.md"
  - "**/.gitignore"
  - "**/.yarnrc.yml"
  - ".devcontainer/*"
  - ".vscode/*"
  - ".husky/*"
  - ".yarn/*"
