#!/usr/bin/env bash

# Only use sudo if not the root user
sudo ()
{
    [[ $(id -u) -eq 0 ]] || set -- command sudo "$@"
    "$@"
}

# Tell APT that we're in a script
export DEBIAN_FRONTEND=noninteractive

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo apt-get update

# get the emacs git snapshot signing key
wget -q http://emacs.ganneff.de/apt.key -O- | sudo apt-key add

# If we're on buster, use backports repo
if [[ $(lsb_release -rs) -le 10 ]]; then
  sudo add-apt-repository "deb http://emacs.ganneff.de/buster main"
  sudo add-apt-repository 'deb http://deb.debian.org/debian buster-backports main'
  sudo apt-get update
  sudo apt-get -y install -t buster-backports --no-install-recommends git-man git
  sudo apt-get -y install -t buster-backports --no-install-recommends fish
else 
  sudo add-apt-repository "deb http://emacs.ganneff.de/bullseye main"
  sudo apt-get update
  sudo apt-get -y install --no-install-recommends git-man git
  sudo apt-get -y install --no-install-recommends fish
fi

sudo apt-get install emacs-snapshot
# sudo update-alternatives --config emacsclient

# Install ripgrep
sudo apt-get -y install --no-install-recommends ripgrep

