ALTER TABLE user_permission ADD COLUMN user_list BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE user_permission ADD COLUMN user_read BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE user_permission ADD COLUMN user_delete BOOLEAN NOT NULL DEFAULT 0;
