ALTER TABLE ebook
ADD COLUMN missing INTEGER NOT NULL DEFAULT 0;

ALTER TABLE audiobook
ADD COLUMN missing INTEGER NOT NULL DEFAULT 0;

ALTER TABLE aligned_book
ADD COLUMN missing INTEGER NOT NULL DEFAULT 0;
