/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export interface Author {
  createdAt: Generated<string>
  fileAs: string
  id: number | null
  name: string
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface AuthorToBook {
  authorUuid: Generated<import("@/uuid").UUID>
  bookUuid: Generated<import("@/uuid").UUID>
  createdAt: Generated<string>
  id: number | null
  role: string | null
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Book {
  alignedAt: string | null
  alignedByStorytellerVersion: string | null
  alignedWith: string | null
  createdAt: Generated<string>
  description: string | null
  id: number | null
  language: Generated<string | null>
  narrator: string | null
  publicationDate: string | null
  rating: number | null
  statusUuid: Generated<import("@/uuid").UUID>
  title: string
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface BookToCollection {
  bookUuid: Generated<import("@/uuid").UUID>
  collectionUuid: Generated<import("@/uuid").UUID>
  createdAt: Generated<string>
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface BookToSeries {
  bookUuid: Generated<import("@/uuid").UUID>
  createdAt: Generated<string>
  featured: Generated<boolean>
  position: number | null
  seriesUuid: Generated<import("@/uuid").UUID>
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface BookToTag {
  bookUuid: Generated<import("@/uuid").UUID>
  createdAt: Generated<string>
  tagUuid: Generated<import("@/uuid").UUID>
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Collection {
  createdAt: Generated<string>
  description: string | null
  name: string
  public: Generated<boolean>
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface CollectionToUser {
  collectionUuid: Generated<import("@/uuid").UUID>
  createdAt: Generated<string>
  updatedAt: Generated<string>
  userUuid: Generated<import("@/uuid").UUID>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Invite {
  createdAt: Generated<string>
  email: string
  id: number | null
  key: string
  updatedAt: Generated<string>
  userPermissionUuid: Generated<import("@/uuid").UUID>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Migration {
  createdAt: Generated<string>
  hash: string
  id: Generated<number>
  name: string
  updatedAt: Generated<string>
}

export interface Position {
  bookUuid: Generated<import("@/uuid").UUID>
  createdAt: Generated<string>
  locator: string
  timestamp: number
  updatedAt: Generated<string>
  userUuid: Generated<import("@/uuid").UUID>
  uuid: Generated<import("@/uuid").UUID>
}

export interface ProcessingTask {
  bookUuid: Generated<import("@/uuid").UUID>
  createdAt: Generated<string>
  id: number | null
  progress: Generated<number>
  status: import("@/apiModels/models/ProcessingStatus").ProcessingTaskStatus
  type: import("@/apiModels/models/ProcessingStatus").ProcessingTaskType
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Series {
  createdAt: Generated<string>
  description: string | null
  name: string
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Settings {
  createdAt: Generated<string>
  id: number | null
  name: keyof typeof import("@/database/settingsTypes").SETTINGS_ROW_NAMES
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
  value: string
}

export interface Status {
  createdAt: Generated<string>
  isDefault: Generated<boolean>
  name: string
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Tag {
  createdAt: Generated<string>
  name: string
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface TokenRevokation {
  createdAt: Generated<string>
  token: string
  updatedAt: Generated<string>
}

export interface User {
  createdAt: Generated<string>
  email: string
  fullName: string
  hashedPassword: string
  id: number | null
  updatedAt: Generated<string>
  username: string
  userPermissionUuid: Generated<import("@/uuid").UUID>
  uuid: Generated<import("@/uuid").UUID>
}

export interface UserPermission {
  bookCreate: Generated<boolean>
  bookDelete: Generated<boolean>
  bookDownload: Generated<boolean>
  bookList: Generated<boolean>
  bookProcess: Generated<boolean>
  bookRead: Generated<boolean>
  bookUpdate: Generated<boolean>
  createdAt: Generated<string>
  id: number | null
  inviteDelete: Generated<boolean>
  inviteList: Generated<boolean>
  settingsUpdate: Generated<boolean>
  updatedAt: Generated<string>
  userCreate: Generated<boolean>
  userDelete: Generated<boolean>
  userList: Generated<boolean>
  userRead: Generated<boolean>
  userUpdate: Generated<boolean>
  uuid: Generated<import("@/uuid").UUID>
}

export interface DB {
  author: Author
  authorToBook: AuthorToBook
  book: Book
  bookToCollection: BookToCollection
  bookToSeries: BookToSeries
  bookToTag: BookToTag
  collection: Collection
  collectionToUser: CollectionToUser
  invite: Invite
  migration: Migration
  position: Position
  processingTask: ProcessingTask
  series: Series
  settings: Settings
  status: Status
  tag: Tag
  tokenRevokation: TokenRevokation
  user: User
  userPermission: UserPermission
}
