/**
 * MARC including Author and Narrator
 */
export const creatorRelators = [
  { label: "Abridger", value: "abr" },
  { label: "Actor", value: "act" },
  { label: "Adapter", value: "adp" },
  { label: "Addressee", value: "rcp" },
  { label: "Analyst", value: "anl" },
  { label: "Animator", value: "anm" },
  { label: "Annotator", value: "ann" },
  { label: "Announcer", value: "anc" },
  { label: "Appellant", value: "apl" },
  { label: "Appellee", value: "ape" },
  { label: "Applicant", value: "app" },
  { label: "Architect", value: "arc" },
  { label: "Arranger", value: "arr" },
  { label: "Art copyist", value: "acp" },
  { label: "Art director", value: "adi" },
  { label: "Artist", value: "art" },
  { label: "Artistic director", value: "ard" },
  { label: "Assignee", value: "asg" },
  { label: "Associated name", value: "asn" },
  { label: "Attributed name", value: "att" },
  { label: "Auctioneer", value: "auc" },
  { label: "Audio engineer", value: "aue" },
  { label: "Audio producer", value: "aup" },
  { label: "Author", value: "aut" },
  { label: "Author in quotations or text abstracts", value: "aqt" },
  { label: "Author of dialog", value: "aud" },
  { label: "Autographer", value: "ato" },
  { label: "Bibliographic antecedent", value: "ant" },
  { label: "Binder", value: "bnd" },
  { label: "Binding designer", value: "bdd" },
  { label: "Blurb writer", value: "blw" },
  { label: "Book artist", value: "bka" },
  { label: "Book designer", value: "bkd" },
  { label: "Book producer", value: "bkp" },
  { label: "Bookjacket designer", value: "bjd" },
  { label: "Bookplate designer", value: "bpd" },
  { label: "Bookseller", value: "bsl" },
  { label: "Braille embosser", value: "brl" },
  { label: "Broadcaster", value: "brd" },
  { label: "Calligrapher", value: "cll" },
  { label: "Camera operator", value: "cop" },
  { label: "Cartographer", value: "ctg" },
  { label: "Caster", value: "cas" },
  { label: "Casting director", value: "cad" },
  { label: "Censor", value: "cns" },
  { label: "Choreographer", value: "chr" },
  { label: "Cinematographer", value: "cng" },
  { label: "Client", value: "cli" },
  { label: "Collection registrar", value: "cor" },
  { label: "Collector", value: "col" },
  { label: "Collotyper", value: "clt" },
  { label: "Colorist", value: "clr" },
  { label: "Commentator", value: "cmm" },
  { label: "Commentator for written text", value: "cwt" },
  { label: "Compiler", value: "com" },
  { label: "Complainant", value: "cpl" },
  { label: "Complainant-appellant", value: "cpt" },
  { label: "Complainant-appellee", value: "cpe" },
  { label: "Composer", value: "cmp" },
  { label: "Compositor", value: "cmt" },
  { label: "Conceptor", value: "ccp" },
  { label: "Conductor", value: "cnd" },
  { label: "Conservator", value: "con" },
  { label: "Consultant", value: "csl" },
  { label: "Consultant to a project", value: "csp" },
  { label: "Contestant", value: "cos" },
  { label: "Contestant-appellant", value: "cot" },
  { label: "Contestant-appellee", value: "coe" },
  { label: "Contestee", value: "cts" },
  { label: "Contestee-appellant", value: "ctt" },
  { label: "Contestee-appellee", value: "cte" },
  { label: "Contractor", value: "ctr" },
  { label: "Contributor", value: "ctb" },
  { label: "Copyright claimant", value: "cpc" },
  { label: "Copyright holder", value: "cph" },
  { label: "Corrector", value: "crr" },
  { label: "Correspondent", value: "crp" },
  { label: "Costume designer", value: "cst" },
  { label: "Court governed", value: "cou" },
  { label: "Court reporter", value: "crt" },
  { label: "Cover designer", value: "cov" },
  { label: "Creator", value: "cre" },
  { label: "Curator", value: "cur" },
  { label: "Dancer", value: "dnc" },
  { label: "Data contributor", value: "dtc" },
  { label: "Data manager", value: "dtm" },
  { label: "Dedicatee", value: "dte" },
  { label: "Dedicator", value: "dto" },
  { label: "Defendant", value: "dfd" },
  { label: "Defendant-appellant", value: "dft" },
  { label: "Defendant-appellee", value: "dfe" },
  { label: "Degree committee member", value: "dgc" },
  { label: "Degree granting institution", value: "dgg" },
  { label: "Degree supervisor", value: "dgs" },
  { label: "Delineator", value: "dln" },
  { label: "Depicted", value: "dpc" },
  { label: "Depositor", value: "dpt" },
  { label: "Designer", value: "dsr" },
  { label: "Director", value: "drt" },
  { label: "Dissertant", value: "dis" },
  { label: "Distribution place", value: "dbp" },
  { label: "Distributor", value: "dst" },
  { label: "Dj", value: "djo" },
  { label: "Donor", value: "dnr" },
  { label: "Draftsman", value: "drm" },
  { label: "Dubbing director", value: "dbd" },
  { label: "Dubious author", value: "dub" },
  { label: "Editor", value: "edt" },
  { label: "Editor of compilation", value: "edc" },
  { label: "Editor of moving image work", value: "edm" },
  { label: "Editorial director", value: "edd" },
  { label: "Electrician", value: "elg" },
  { label: "Electrotyper", value: "elt" },
  { label: "Enacting jurisdiction", value: "enj" },
  { label: "Engineer", value: "eng" },
  { label: "Engraver", value: "egr" },
  { label: "Etcher", value: "etr" },
  { label: "Event place", value: "evp" },
  { label: "Expert", value: "exp" },
  { label: "Facsimilist", value: "fac" },
  { label: "Field director", value: "fld" },
  { label: "Film director", value: "fmd" },
  { label: "Film distributor", value: "fds" },
  { label: "Film editor", value: "flm" },
  { label: "Film producer", value: "fmp" },
  { label: "Filmmaker", value: "fmk" },
  { label: "First party", value: "fpy" },
  { label: "Forger", value: "frg" },
  { label: "Former owner", value: "fmo" },
  { label: "Founder", value: "fon" },
  { label: "Funder", value: "fnd" },
  { label: "Game developer", value: "gdv" },
  { label: "Geographic information specialist", value: "gis" },
  { label: "Honoree", value: "hnr" },
  { label: "Host", value: "hst" },
  { label: "Host institution", value: "his" },
  { label: "Illuminator", value: "ilu" },
  { label: "Illustrator", value: "ill" },
  { label: "Inker", value: "ink" },
  { label: "Inscriber", value: "ins" },
  { label: "Instrumentalist", value: "itr" },
  { label: "Interviewee", value: "ive" },
  { label: "Interviewer", value: "ivr" },
  { label: "Inventor", value: "inv" },
  { label: "Issuing body", value: "isb" },
  { label: "Judge", value: "jud" },
  { label: "Jurisdiction governed", value: "jug" },
  { label: "Laboratory", value: "lbr" },
  { label: "Laboratory director", value: "ldr" },
  { label: "Landscape architect", value: "lsa" },
  { label: "Lead", value: "led" },
  { label: "Lender", value: "len" },
  { label: "Letterer", value: "ltr" },
  { label: "Libelant", value: "lil" },
  { label: "Libelant-appellant", value: "lit" },
  { label: "Libelant-appellee", value: "lie" },
  { label: "Libelee", value: "lel" },
  { label: "Libelee-appellant", value: "let" },
  { label: "Libelee-appellee", value: "lee" },
  { label: "Librettist", value: "lbt" },
  { label: "Licensee", value: "lse" },
  { label: "Licensor", value: "lso" },
  { label: "Lighting designer", value: "lgd" },
  { label: "Lithographer", value: "ltg" },
  { label: "Lyricist", value: "lyr" },
  { label: "Makeup artist", value: "mka" },
  { label: "Manufacture place", value: "mfp" },
  { label: "Manufacturer", value: "mfr" },
  { label: "Marbler", value: "mrb" },
  { label: "Markup editor", value: "mrk" },
  { label: "Medium", value: "med" },
  { label: "Metadata contact", value: "mdc" },
  { label: "Metal-engraver", value: "mte" },
  { label: "Minute taker", value: "mtk" },
  { label: "Mixing engineer", value: "mxe" },
  { label: "Moderator", value: "mod" },
  { label: "Monitor", value: "mon" },
  { label: "Music copyist", value: "mcp" },
  { label: "Music programmer", value: "mup" },
  { label: "Musical director", value: "msd" },
  { label: "Musician", value: "mus" },
  { label: "Narrator", value: "nrt" },
  { label: "News anchor", value: "nan" },
  { label: "Onscreen participant", value: "onp" },
  { label: "Onscreen presenter", value: "osp" },
  { label: "Opponent", value: "opn" },
  { label: "Organizer", value: "orm" },
  { label: "Originator", value: "org" },
  { label: "Other", value: "oth" },
  { label: "Owner", value: "own" },
  { label: "Panelist", value: "pan" },
  { label: "Papermaker", value: "ppm" },
  { label: "Patent applicant", value: "pta" },
  { label: "Patent holder", value: "pth" },
  { label: "Patron", value: "pat" },
  { label: "Penciller", value: "pnc" },
  { label: "Performer", value: "prf" },
  { label: "Permitting agency", value: "pma" },
  { label: "Photographer", value: "pht" },
  { label: "Place of address", value: "pad" },
  { label: "Plaintiff", value: "ptf" },
  { label: "Plaintiff-appellant", value: "ptt" },
  { label: "Plaintiff-appellee", value: "pte" },
  { label: "Platemaker", value: "plt" },
  { label: "Praeses", value: "pra" },
  { label: "Presenter", value: "pre" },
  { label: "Printer", value: "prt" },
  { label: "Printer of plates", value: "pop" },
  { label: "Printmaker", value: "prm" },
  { label: "Process contact", value: "prc" },
  { label: "Producer", value: "pro" },
  { label: "Production company", value: "prn" },
  { label: "Production designer", value: "prs" },
  { label: "Production manager", value: "pmn" },
  { label: "Production personnel", value: "prd" },
  { label: "Production place", value: "prp" },
  { label: "Programmer", value: "prg" },
  { label: "Project director", value: "pdr" },
  { label: "Proofreader", value: "pfr" },
  { label: "Provider", value: "prv" },
  { label: "Publication place", value: "pup" },
  { label: "Publisher", value: "pbl" },
  { label: "Publishing director", value: "pbd" },
  { label: "Puppeteer", value: "ppt" },
  { label: "Radio director", value: "rdd" },
  { label: "Radio producer", value: "rpc" },
  { label: "Rapporteur", value: "rap" },
  { label: "Recording engineer", value: "rce" },
  { label: "Recordist", value: "rcd" },
  { label: "Redaktor", value: "red" },
  { label: "Remix artist", value: "rxa" },
  { label: "Renderer", value: "ren" },
  { label: "Reporter", value: "rpt" },
  { label: "Repository", value: "rps" },
  { label: "Research team head", value: "rth" },
  { label: "Research team member", value: "rtm" },
  { label: "Researcher", value: "res" },
  { label: "Respondent", value: "rsp" },
  { label: "Respondent-appellant", value: "rst" },
  { label: "Respondent-appellee", value: "rse" },
  { label: "Responsible party", value: "rpy" },
  { label: "Restager", value: "rsg" },
  { label: "Restorationist", value: "rsr" },
  { label: "Reviewer", value: "rev" },
  { label: "Rubricator", value: "rbr" },
  { label: "Scenarist", value: "sce" },
  { label: "Scientific advisor", value: "sad" },
  { label: "Screenwriter", value: "aus" },
  { label: "Scribe", value: "scr" },
  { label: "Sculptor", value: "scl" },
  { label: "Second party", value: "spy" },
  { label: "Secretary", value: "sec" },
  { label: "Seller", value: "sll" },
  { label: "Set designer", value: "std" },
  { label: "Setting", value: "stg" },
  { label: "Signer", value: "sgn" },
  { label: "Singer", value: "sng" },
  { label: "Software developer", value: "swd" },
  { label: "Sound designer", value: "sds" },
  { label: "Sound engineer", value: "sde" },
  { label: "Speaker", value: "spk" },
  { label: "Special effects provider", value: "sfx" },
  { label: "Sponsor", value: "spn" },
  { label: "Stage director", value: "sgd" },
  { label: "Stage manager", value: "stm" },
  { label: "Standards body", value: "stn" },
  { label: "Stereotyper", value: "str" },
  { label: "Storyteller", value: "stl" },
  { label: "Supporting host", value: "sht" },
  { label: "Surveyor", value: "srv" },
  { label: "Teacher", value: "tch" },
  { label: "Technical advisor", value: "tad" },
  { label: "Technical director", value: "tcd" },
  { label: "Television director", value: "tld" },
  { label: "Television guest", value: "tlg" },
  { label: "Television host", value: "tlh" },
  { label: "Television producer", value: "tlp" },
  { label: "Television writer", value: "tau" },
  { label: "Thesis advisor", value: "ths" },
  { label: "Transcriber", value: "trc" },
  { label: "Translator", value: "trl" },
  { label: "Type designer", value: "tyd" },
  { label: "Typographer", value: "tyg" },
  { label: "University place", value: "uvp" },
  { label: "Videographer", value: "vdg" },
  { label: "Visual effects provider", value: "vfx" },
  { label: "Voice actor", value: "vac" },
  { label: "Witness", value: "wit" },
  { label: "Wood engraver", value: "wde" },
  { label: "Woodcutter", value: "wdc" },
  { label: "Writer of accompanying material", value: "wam" },
  { label: "Writer of added commentary", value: "wac" },
  { label: "Writer of added lyrics", value: "wal" },
  { label: "Writer of added text", value: "wat" },
  { label: "Writer of afterword", value: "waw" },
  { label: "Writer of film story", value: "wfs" },
  { label: "Writer of foreword", value: "wfw" },
  { label: "Writer of intertitles", value: "wft" },
  { label: "Writer of introduction", value: "win" },
  { label: "Writer of preface", value: "wpr" },
  { label: "Writer of supplementary textual content", value: "wst" },
  { label: "Writer of television story", value: "wts" },
] as const

/**
 * Possible role for a creator
 */
export type Role = (typeof creatorRelators)[number]["value"]

export const isRole = (role: string): role is Role =>
  creatorRelators.some((r) => r.value === role)

/**
 * Possible role for a creator, excluding Author and Narrator
 */
export type MarcRole = Exclude<Role, "aut" | "nrt">

/**
 * All possible MARC relators, excluding Author and Narrator
 */
export const marcRelators = creatorRelators.filter(
  (r) => r.value !== "aut" && r.value !== "nrt",
) as { value: MarcRole; label: string }[]
